### ISSUE TITLE
Wrong import for CheckoutPaymentType in 2205_6 release

### ISSUE THREAD

**Issue by mohsen-saeidi** [Worldpay/hybris#127]
Hi,

Unfortunately, I am getting a compilation error with the 2205_6 release. It was working fine until 2205_3 version and after that, I see that you changed the import for CheckoutPaymentType from 
`import de.hybris.platform.b2bacceleratorservices.enums.CheckoutPaymentType;`
to
`import de.hybris.platform.b2b.enums.CheckoutPaymentType;`
in WorldpayB2BAcceleratorCheckoutFacadeDecorator class and this has a compilation error.

The definition for CheckoutPaymentType is in b2bacceleratorservices-items.xml as below:
```
<enumtype generate="true" code="CheckoutPaymentType" autocreate="true" dynamic="true">
	<description>This enum type will be used for selecting checkout Payment Type</description>
	<value code="CARD"/>
	<value code="ACCOUNT"/>
</enumtype>
```
It seems the change happened in the 2205_4 release with [this commit](https://github.com/Worldpay/hybris/commit/c6d8cf22c1b57eb1ec61d7d20ffa1ff4d9a770d3): 
So it should be in de.hybris.platform.b2bacceleratorservices.enums. and not in de.hybris.platform.b2b.enums
Would you please fix it? 

best,

**Comment by adbame** [comment]
Thanks @mohsen-saeidi We are looking into this and will respond to your comments in due course. Thank you for your insight.

**Comment by adbame** [comment]
Hello @mohsen-saeidi 
A new version has been released fixing the error

Thank you
