### ISSUE TITLE
`java.lang.ClassCastException` when a worldpay order code relates to a cart that has the transaction type set to `AUTHORIZATION`

### ISSUE THREAD

**Issue by 1gmar** [Worldpay/hybris#74]
Hello again, worldpay team, we've encountered another issue with the latest [1905_7.0 release](https://github.com/Worldpay/hybris/releases/tag/release_1905_7.0):

When the new `DefaultWorldpayOrderModificationProcessService` has been introduced, a class cast has creeped out of the `if` branch on this [line](https://github.com/Worldpay/hybris/blob/65d3a8079bae128cf4bf238ab030070960aa1496/hybris/bin/y-ext/ext-worldpay/worldpaynotifications/src/com/worldpay/core/services/impl/DefaultWorldpayOrderModificationProcessService.java#L98). This causes an unhandled `ClassCastException` which crashes the `OrderModificationProcessorJobPerformable` completely and orders are stuck in `Pending Payment Notification` status.

Here is a unit test which you can add to `DefaultWorldpayOrderModificationProcessServiceTest` to reproduce the issue:
```
@Test
public void processOrderModificationMessages_WhenWorldpayOrderCodeRelatesToCartWithAuthorizationTransactionType_ShouldDoNothing() throws WorldpayConfigurationException {
    when(paymentTransactionModelMock.getOrder()).thenReturn(cartModelMock);

    final boolean result = testObj.processOrderModificationMessages(AUTHORIZATION);

    assertTrue(result);
    verify(worldpayOrderNotificationHandlerMock, never()).handleNotificationBusinessProcess(AUTHORIZATION, worldpayOrderModificationMock, orderModelMock, orderNotificationMessageMock);
    verify(worldpayOrderModificationMock, never()).setProcessed(Boolean.TRUE);
    verify(worldpayOrderModificationMock, never()).setDefective(any(Boolean.class));
}
```
Thank you for your support.

Regards.

**Comment by slav-pilus** [comment]
This is still a problem I've seen in production - it needs fixing

**Comment by Magdoosha** [comment]
Thanks @slav-pilus for flagging this up. We are looking into this and will be back in touch in due course.

**Comment by adbame** [comment]
Hello @slav-pilus 

A new release has been published for versions 2211, 2205 and 2105 fixing this issue
