### ISSUE TITLE
Change PAYPAL-EXPRESS to PAYPAL-SSL

### ISSUE THREAD

**Issue by mohsen-saeidi** [Worldpay/hybris#82]
Hi, as Worldpay notified they are going to change the type PAYPAL-EXPRESS to PAYPAL-SSL. I just want to ask do you have any plans to fix it in this project?
Kind regards,
Mohsen

**Comment by adbame** [comment]
Hello @mohsen-saeidi 

PAYPAL-SSL was released 3 weeks ago

Kind regards
